<nav>
	<label for='toggler'>
		<img src='./images/icon-menu.svg' alt='Hamburger Menu' width='48' height='48'>
	</label>
	<a href='./'><img src='./images/logo.svg' alt='AvtoZeichen Logo' width='130' height='52'></a>
	<ul>
		<li><a href='./jobs.php'>Jobs</a></li>
		<li><a href='./apply.php'>Apply</a></li>
		<li><a href='./about.php'>About us</a></li>
		<li><a href='./manage.php'>EOI Manager</a></li>
		<li><a href='./phpenhancements.php'>PHP Enhancements</a></li>
		<li><a href='mailto:104993913@student.swin.edu.au'>Contact us</a></li>
	</ul>
	<img src='./images/icon-menu.svg' alt='AntiBurger Menu' width='48' height='48' class='hidden'>
</nav>
