<footer>
	<a href='./'><img src='./images/logo.svg' alt='AvtoZeichen Logo' width='130' height='52' id='footer-logo'></a>
	<ul>
		<li><a href='./jobs.php'>Jobs</a></li>
		<li><a href='./apply.php'>Apply</a></li>
		<li><a href='./about.php'>About us</a></li>
		<li><a href='./manage.php'>EOI Manager</a></li>
		<li><a href='./enhancements.php'>Enhancements</a></li>
		<li><a href='./phpenhancements.php'>PHP Enhancements</a></li>
		<li><a href='mailto:104993913@student.swin.edu.au'>Contact us</a></li>
	</ul>
	<p>
		&copy; 2024 AvtoZeichen. Designed by <a href='./about.php'>The&nbsp;Internerdt</a>.
		Hero image belongs to author ŠJů and uploaded to
		<a href='https://commons.wikimedia.org/wiki/File:Nov%C3%A1_Povltavsk%C3%A1,_Ho%C5%99%C3%AD_v_tunelu_(01).jpg'
			class='text-yellow'>Wikimedia Commons</a>
	</p>
</footer>
