<input type='checkbox' id='toggler'>
<aside class='burger-menu'>
	<label for='toggler'>
		<img src='./images/icon-exit.svg' alt='Hamburger Menu' width='48' height='48'>
	</label>

	<ul>
		<li><a href='./'>Home</a></li>
		<li><a href='./jobs.php'>Jobs</a></li>
		<li><a href='./apply.php'>Apply</a></li>
		<li><a href='./about.php'>About us</a></li>
		<li><a href='./manage.php'>EOI Manager</a></li>
		<li><a href='./phpenhancements.php'>PHP Enhancements</a></li>
	</ul>

	<ul>
		<li><a href='mailto:104993913@student.swin.edu.au'>Contact us</a></li>
	</ul>
</aside>
