services:
  web:
    build: .
    ports:
      - 80:80
    environment:
      DB_HOSTNAME: db
      DB_USERNAME: az_web_user
      DB_PASSWORD: az_Pa55w.rd
      DB_DATABASE: avtozeichen
    deploy:
      resources:
        limits:
          memory: 64M

  db:
    image: mariadb:lts-ubi9
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: az_R00t_Pa55w.rd
      MYSQL_DATABASE: avtozeichen
      MYSQL_USER: az_web_user
      MYSQL_PASSWORD: az_Pa55w.rd
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
    db_data:
